package io.battlerune.content;

/**
 * The activity log class.
 *
 * @author Daniel
 */
public enum ActivityLog {
	/* Activities */
	BARROWS, FIGHT_CAVES,ALLVSONE, ALLVSONE2, PEST_CONTROL, KOLODIONS_MINIGAME, CRYSTAL_CHEST, EASY_CLUE, MEDIUM_CLUE, HARD_CLUE,
	ELITE_CLUE, INFERNO, ALLVSONE3, Double_Threat,

	/* Bosses */
	SKOTIZO, GLOD, PORAZDIR, GANO, GALVEK, ZULRAH, CORPOREAL_BEAST, KING_BLACK_DRAGON, CHAOS_ELEMENTAL, CHAOS_FANATIC,
	CRAZY_ARCHAEOLOGIST, CALLISTO, SCORPIA, VENANTIS, VETION, KRAKEN, COMMANDER_ZILYANA, GENERAL_GRAARDOR,
	KRIL_TSUTSAROTH, KREE_ARRA, CERBERUS, JUSTICAR, CHIMERA, GIANT_MOLE, DAGGANOTH_SUPREME, DAGGANOTH_PRIME, DAGGANOTH_REX,

	/* Regular monsters */
	SKELETAL_WYVERN, ABYSSAL_DEMON, LIZARDMAN_SHAMAN, GIANT_ROC, MITHRIL_DRAGON, DARK_BEAST, MAN, LAVA_DRAGON, VORKATH, ICE_DEMON, MUTANT_TARN,
}
